/**
 * Root ESLint config — re-exports the shared React preset from @lumiris/config.
 * Used by lint-staged at the repo root; per-workspace configs (apps/*, packages/*)
 * still take precedence inside their directories when ESLint is invoked there.
 */
import react from '@lumiris/config/eslint/react';

export default [
    ...react,
    {
        // Shadcn primitives are kept as-generated by the CLI. Mirror the override
        // from `packages/ui/eslint.config.mjs` so lint-staged at the repo root
        // does not flag them.
        files: ['packages/ui/src/components/ui/**/*.{ts,tsx}'],
        rules: {
            'jsx-a11y/anchor-has-content': 'off',
            'jsx-a11y/click-events-have-key-events': 'off',
            'jsx-a11y/no-noninteractive-element-interactions': 'off',
            'jsx-a11y/no-static-element-interactions': 'off',
            'react/no-danger': 'off',
            '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_|^[A-Z]' }],
        },
    },
    {
        ignores: [
            '**/node_modules/**',
            '**/.next/**',
            '**/dist/**',
            '**/build/**',
            '**/.turbo/**',
            '**/coverage/**',
            '**/out/**',
            '**/src-tauri/target/**',
        ],
    },
];
