import type { AdminAuditLogEntry } from '@lumiris/types';

// 50 entrées sur 30 jours — l'app admin accumule de nouvelles entrées via lib/auth/audit.tsx

const DAY_MS = 86_400_000;
const BASE = new Date('2026-04-30T08:00:00Z').getTime();
function ts(daysAgo: number, hour = 9, minute = 0): string {
    return new Date(BASE - daysAgo * DAY_MS + hour * 3_600_000 + minute * 60_000).toISOString();
}

export const mockAdminAuditLog: readonly AdminAuditLogEntry[] = [
    {
        id: 'LOG-001',
        ts: ts(0, 8, 12),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-042',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-002',
        ts: ts(0, 9, 30),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-017',
        payload: { decision: 'Rejected', reason: 'Photos manquantes' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-003',
        ts: ts(0, 10, 5),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'passport.override_score',
        targetType: 'passport',
        targetId: 'PASS-099',
        payload: { from: 'D', to: 'C', reason: 'Cap AGEC réfuté' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-004',
        ts: ts(1, 14, 15),
        actorId: 'ADM-004',
        actorRole: 'content_manager',
        action: 'blog.publish',
        targetType: 'article',
        targetId: 'ART-FR-001',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-005',
        ts: ts(1, 16, 22),
        actorId: 'ADM-005',
        actorRole: 'billing_ops',
        action: 'billing.dunning',
        targetType: 'artisan',
        targetId: 'ART-04',
        payload: { stage: 'reminder-3' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-006',
        ts: ts(2, 9, 0),
        actorId: 'ADM-006',
        actorRole: 'dpo',
        action: 'vision_user.export_rgpd',
        targetType: 'vision_user',
        targetId: 'VIS-014',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-007',
        ts: ts(2, 11, 40),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-068',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-008',
        ts: ts(2, 15, 5),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-021',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-009',
        ts: ts(3, 10, 18),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'artisan.suspend',
        targetType: 'artisan',
        targetId: 'ART-11',
        payload: { reason: 'Facture suspecte' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-010',
        ts: ts(3, 13, 47),
        actorId: 'ADM-005',
        actorRole: 'billing_ops',
        action: 'billing.export',
        targetType: 'period',
        targetId: '2026-Q1',
        payload: { format: 'csv' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-011',
        ts: ts(4, 9, 22),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-104',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-012',
        ts: ts(4, 11, 5),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-088',
        payload: { decision: 'Rejected', reason: 'Composition incohérente' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-013',
        ts: ts(5, 8, 30),
        actorId: 'ADM-006',
        actorRole: 'dpo',
        action: 'vision_user.erase_rgpd',
        targetType: 'vision_user',
        targetId: 'VIS-007',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-014',
        ts: ts(5, 14, 12),
        actorId: 'ADM-004',
        actorRole: 'content_manager',
        action: 'blog.publish',
        targetType: 'article',
        targetId: 'ART-FR-002',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-015',
        ts: ts(6, 10, 0),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'retoucheur.verify_kyc',
        targetType: 'repairer',
        targetId: 'RTC-009',
        payload: { decision: 'verified' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-016',
        ts: ts(6, 15, 33),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-031',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-017',
        ts: ts(7, 9, 18),
        actorId: 'ADM-005',
        actorRole: 'billing_ops',
        action: 'affiliation.prepare_payout',
        targetType: 'period',
        targetId: '2026-04',
        payload: { eligibleEvents: 142 },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-018',
        ts: ts(7, 11, 27),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-055',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-019',
        ts: ts(8, 14, 0),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'artisan.contact',
        targetType: 'artisan',
        targetId: 'ART-22',
        payload: { channel: 'email' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-020',
        ts: ts(8, 16, 50),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-073',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-021',
        ts: ts(9, 10, 22),
        actorId: 'ADM-006',
        actorRole: 'dpo',
        action: 'vision_user.export_rgpd',
        targetType: 'vision_user',
        targetId: 'VIS-022',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-022',
        ts: ts(9, 13, 11),
        actorId: 'ADM-004',
        actorRole: 'content_manager',
        action: 'blog.archive',
        targetType: 'article',
        targetId: 'ART-002',
        payload: { reason: 'Outdated' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-023',
        ts: ts(10, 8, 45),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-018',
        payload: { decision: 'Rejected', reason: 'Origin missing' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-024',
        ts: ts(10, 15, 30),
        actorId: 'ADM-005',
        actorRole: 'billing_ops',
        action: 'billing.dunning',
        targetType: 'artisan',
        targetId: 'ART-12',
        payload: { stage: 'reminder-2' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-025',
        ts: ts(11, 9, 15),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'passport.override_score',
        targetType: 'passport',
        targetId: 'PASS-112',
        payload: { from: 'C', to: 'B', reason: 'Manual review confirmed' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-026',
        ts: ts(12, 10, 5),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-094',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-027',
        ts: ts(12, 14, 22),
        actorId: 'ADM-007',
        actorRole: 'platform_admin',
        action: 'retoucheur.suspend',
        targetType: 'repairer',
        targetId: 'RTC-021',
        payload: { reason: 'Multiple complaints' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-028',
        ts: ts(13, 11, 0),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-067',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-029',
        ts: ts(14, 9, 30),
        actorId: 'ADM-004',
        actorRole: 'content_manager',
        action: 'blog.publish',
        targetType: 'article',
        targetId: 'ART-FR-003',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-030',
        ts: ts(15, 10, 18),
        actorId: 'ADM-006',
        actorRole: 'dpo',
        action: 'governance.read_audit_log',
        targetType: 'period',
        targetId: 'last-7d',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-031',
        ts: ts(15, 14, 0),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-082',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-032',
        ts: ts(16, 10, 45),
        actorId: 'ADM-005',
        actorRole: 'billing_ops',
        action: 'affiliation.read',
        targetType: 'period',
        targetId: '2026-03',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-033',
        ts: ts(17, 11, 22),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-026',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-034',
        ts: ts(17, 16, 8),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'artisan.suspend',
        targetType: 'artisan',
        targetId: 'ART-29',
        payload: { reason: 'Inactivity 90d' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-035',
        ts: ts(18, 9, 0),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-040',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-036',
        ts: ts(19, 13, 50),
        actorId: 'ADM-007',
        actorRole: 'platform_admin',
        action: 'passport.override_score',
        targetType: 'passport',
        targetId: 'PASS-013',
        payload: { from: 'B', to: 'A', reason: 'Cert OFG re-validated' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-037',
        ts: ts(20, 10, 15),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-061',
        payload: { decision: 'Rejected', reason: 'Photos not GDPR-compliant' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-038',
        ts: ts(21, 11, 33),
        actorId: 'ADM-004',
        actorRole: 'content_manager',
        action: 'blog.publish',
        targetType: 'article',
        targetId: 'ART-FR-004',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-039',
        ts: ts(22, 14, 10),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-091',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-040',
        ts: ts(23, 9, 27),
        actorId: 'ADM-005',
        actorRole: 'billing_ops',
        action: 'billing.dunning',
        targetType: 'artisan',
        targetId: 'ART-19',
        payload: { stage: 'reminder-1' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-041',
        ts: ts(24, 10, 5),
        actorId: 'ADM-006',
        actorRole: 'dpo',
        action: 'vision_user.read',
        targetType: 'vision_user',
        targetId: 'VIS-031',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-042',
        ts: ts(25, 11, 50),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'artisan.contact',
        targetType: 'artisan',
        targetId: 'ART-07',
        payload: { channel: 'phone' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-043',
        ts: ts(26, 13, 14),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-049',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-044',
        ts: ts(27, 9, 40),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-115',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-045',
        ts: ts(27, 15, 22),
        actorId: 'ADM-004',
        actorRole: 'content_manager',
        action: 'blog.archive',
        targetType: 'article',
        targetId: 'ART-005',
        payload: { reason: 'Replaced' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-046',
        ts: ts(28, 10, 0),
        actorId: 'ADM-007',
        actorRole: 'platform_admin',
        action: 'retoucheur.verify_kyc',
        targetType: 'repairer',
        targetId: 'RTC-014',
        payload: { decision: 'verified' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-047',
        ts: ts(29, 14, 47),
        actorId: 'ADM-005',
        actorRole: 'billing_ops',
        action: 'affiliation.prepare_payout',
        targetType: 'period',
        targetId: '2026-03',
        payload: { eligibleEvents: 168 },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-048',
        ts: ts(29, 16, 30),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'PASS-076',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-049',
        ts: ts(30, 11, 18),
        actorId: 'ADM-006',
        actorRole: 'dpo',
        action: 'vision_user.export_rgpd',
        targetType: 'vision_user',
        targetId: 'VIS-039',
        payload: {},
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-050',
        ts: ts(30, 14, 0),
        actorId: 'ADM-001',
        actorRole: 'platform_admin',
        action: 'governance.read_audit_log',
        targetType: 'period',
        targetId: 'last-30d',
        payload: {},
        ipMock: '127.0.0.1',
    },

    // entrées ciblant les passeports réels de passports.ts (drawer Historique)
    {
        id: 'LOG-101',
        ts: ts(58, 9, 12),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.request_changes',
        targetType: 'passport',
        targetId: 'pass-marie-001',
        payload: { message: 'Manque photo étape 3', tags: ['photos'] },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-102',
        ts: ts(57, 10, 0),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'pass-marie-001',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-103',
        ts: ts(45, 14, 22),
        actorId: 'ADM-008',
        actorRole: 'lead_curator',
        action: 'passport.override_score',
        targetType: 'passport',
        targetId: 'pass-paul-001',
        payload: { from: 'B', to: 'A', reason: 'EPV re-vérifié + cuir tannage végétal documenté' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-104',
        ts: ts(40, 11, 5),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.flag',
        targetType: 'passport',
        targetId: 'pass-soraya-001',
        payload: { reason: 'Certif Oeko expirée non remplacée', tags: ['certif_expire'] },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-105',
        ts: ts(35, 9, 0),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'pass-amelie-001',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-106',
        ts: ts(28, 16, 20),
        actorId: 'ADM-003',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'pass-laurens-001',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-107',
        ts: ts(20, 11, 30),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'passport',
        targetId: 'pass-claire-001',
        payload: { decision: 'Approved' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-108',
        ts: ts(15, 13, 50),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.request_changes',
        targetType: 'passport',
        targetId: 'pass-pauline-002-incomplet',
        payload: {
            message: 'Composition à 100% chanvre — il manque les étapes de fab',
            tags: ['etapes', 'composition'],
        },
        ipMock: '127.0.0.1',
    },

    // anomalies pour le module governance — pattern 1 : >3 validations art-marie en <5 min (chaîne suspecte)
    {
        id: 'LOG-201',
        ts: ts(2, 11, 0),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'artisan',
        targetId: 'art-marie',
        payload: { decision: 'Approved', passportId: 'pass-marie-001' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-202',
        ts: ts(2, 11, 1),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'artisan',
        targetId: 'art-marie',
        payload: { decision: 'Approved', passportId: 'pass-marie-002' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-203',
        ts: ts(2, 11, 2),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'artisan',
        targetId: 'art-marie',
        payload: { decision: 'Approved', passportId: 'pass-marie-003' },
        ipMock: '127.0.0.1',
    },
    {
        id: 'LOG-204',
        ts: ts(2, 11, 3),
        actorId: 'ADM-002',
        actorRole: 'curator',
        action: 'passport.curate',
        targetType: 'artisan',
        targetId: 'art-marie',
        payload: { decision: 'Approved', passportId: 'pass-marie-004' },
        ipMock: '127.0.0.1',
    },
];
