import type { AdminUser } from '@lumiris/types';

// 7 admins (un par rôle) - index 0 doit rester platform_admin pour donner full access en dev
export const mockAdminUsers: readonly AdminUser[] = [
    {
        id: 'ADM-001',
        email: 'lea.marchand@lumiris.fr',
        fullName: 'Léa Marchand',
        role: 'platform_admin',
        avatarUrl: 'https://cdn.lumiris.local/admins/lea.jpg',
        createdAt: '2025-01-15T08:00:00Z',
        lastSeenAt: '2026-04-30T07:42:00Z',
    },
    {
        id: 'ADM-002',
        email: 'antoine.berger@lumiris.fr',
        fullName: 'Antoine Berger',
        role: 'curator',
        avatarUrl: 'https://cdn.lumiris.local/admins/antoine.jpg',
        createdAt: '2025-03-04T08:00:00Z',
        lastSeenAt: '2026-04-29T18:15:00Z',
    },
    {
        id: 'ADM-003',
        email: 'sophie.duval@lumiris.fr',
        fullName: 'Sophie Duval',
        role: 'curator',
        avatarUrl: 'https://cdn.lumiris.local/admins/sophie.jpg',
        createdAt: '2025-05-20T08:00:00Z',
        lastSeenAt: '2026-04-30T09:10:00Z',
    },
    {
        id: 'ADM-004',
        email: 'claire.dubois@lumiris.fr',
        fullName: 'Claire Dubois',
        role: 'content_manager',
        avatarUrl: 'https://cdn.lumiris.local/admins/claire.jpg',
        createdAt: '2025-02-10T08:00:00Z',
        lastSeenAt: '2026-04-30T06:50:00Z',
    },
    {
        id: 'ADM-005',
        email: 'thomas.morel@lumiris.fr',
        fullName: 'Thomas Morel',
        role: 'billing_ops',
        avatarUrl: 'https://cdn.lumiris.local/admins/thomas.jpg',
        createdAt: '2025-06-15T08:00:00Z',
        lastSeenAt: '2026-04-29T16:00:00Z',
    },
    {
        id: 'ADM-006',
        email: 'nadia.khelifi@lumiris.fr',
        fullName: 'Nadia Khelifi',
        role: 'dpo',
        avatarUrl: 'https://cdn.lumiris.local/admins/nadia.jpg',
        createdAt: '2025-04-08T08:00:00Z',
        lastSeenAt: '2026-04-28T14:20:00Z',
    },
    {
        id: 'ADM-007',
        email: 'maxime.laurent@lumiris.fr',
        fullName: 'Maxime Laurent',
        role: 'platform_admin',
        avatarUrl: 'https://cdn.lumiris.local/admins/maxime.jpg',
        createdAt: '2026-02-01T08:00:00Z',
        lastSeenAt: '2026-04-30T08:30:00Z',
    },
    {
        id: 'ADM-008',
        email: 'agathe.gervais@lumiris.fr',
        fullName: 'Agathe Gervais',
        role: 'lead_curator',
        avatarUrl: 'https://cdn.lumiris.local/admins/agathe.jpg',
        createdAt: '2025-04-15T08:00:00Z',
        lastSeenAt: '2026-04-30T07:55:00Z',
    },
];
