import type { Artisan } from '@lumiris/types';
import { ARTISAN_PASSPORT_LIMIT } from '@lumiris/types';
import { slugify } from '@lumiris/utils';

// 12 artisans (8 Solo / 3 Studio / 1 Maison, 4 EPV) - personas Marie + Théo inclus
export const mockArtisans: readonly Artisan[] = [
    {
        id: 'art-marie',
        displayName: 'Marie Le Goff',
        atelierName: 'Atelier de Marie',
        city: 'Quimper',
        region: 'Bretagne',
        tier: 'Solo',
        plus: false,
        epvLabeled: false,
        ofgLabeled: true,
        specialities: ['Couture haute façon', 'Lin tissé'],
        story: 'Couturière formée aux Compagnons du Devoir, installée à Quimper depuis 2019. Travaille exclusivement le lin breton, teint en local.',
        photoUrl: 'https://placehold.co/256x256/oklch/65/0.13/195/png?text=Marie',
        websiteUrl: 'https://atelierdemarie.fr',
        joinedAt: '2025-06-15T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-theo',
        displayName: 'Théo Magnan',
        atelierName: 'Maison Magnan',
        city: 'Romans-sur-Isère',
        region: 'Auvergne-Rhône-Alpes',
        tier: 'Studio',
        plus: true,
        epvLabeled: true,
        ofgLabeled: false,
        specialities: ['Cordonnerie', 'Cuir tannage végétal'],
        story: 'Chausseur de troisième génération à Romans-sur-Isère. Studio de 4 personnes, EPV depuis 2018.',
        photoUrl: 'https://placehold.co/256x256/oklch/64/0.18/45/png?text=Theo',
        websiteUrl: 'https://maison-magnan.fr',
        joinedAt: '2024-11-02T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Studio,
    },
    {
        id: 'art-claire',
        displayName: 'Claire Vidal',
        atelierName: "L'atelier des Hauts",
        city: 'Lille',
        region: 'Hauts-de-France',
        tier: 'Solo',
        plus: false,
        epvLabeled: false,
        ofgLabeled: false,
        specialities: ['Tricot main', 'Laine mérinos'],
        story: 'Tricoteuse à la main installée à Lille. Passeport limité à des séries de 5 à 20 pièces.',
        photoUrl: 'https://placehold.co/256x256/oklch/55/0.18/160/png?text=Claire',
        websiteUrl: 'https://atelierdeshauts.fr',
        joinedAt: '2025-09-12T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-paul',
        displayName: 'Paul Chevreau',
        atelierName: 'Tannerie Chevreau',
        city: 'Graulhet',
        region: 'Occitanie',
        tier: 'Studio',
        plus: true,
        epvLabeled: true,
        ofgLabeled: false,
        specialities: ['Tannage végétal', 'Maroquinerie'],
        story: 'Tannerie familiale fondée en 1947 à Graulhet, EPV. Cuirs tannage végétal pour maroquinerie haut de gamme.',
        photoUrl: 'https://placehold.co/256x256/oklch/72/0.16/85/png?text=Paul',
        websiteUrl: 'https://tannerie-chevreau.fr',
        joinedAt: '2024-09-01T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Studio,
    },
    {
        id: 'art-amelie',
        displayName: 'Amélie Berthier',
        atelierName: 'Berthier Brodeuse',
        city: 'Lyon',
        region: 'Auvergne-Rhône-Alpes',
        tier: 'Solo',
        plus: false,
        epvLabeled: true,
        ofgLabeled: false,
        specialities: ['Broderie main', 'Soie de Lyon'],
        story: 'Brodeuse main, EPV depuis 2021, ancienne Compagnonne. Travaille pour la haute couture parisienne.',
        photoUrl: 'https://placehold.co/256x256/oklch/55/0.20/15/png?text=Amelie',
        websiteUrl: 'https://berthier-broderie.fr',
        joinedAt: '2025-02-10T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-nicolas',
        displayName: 'Nicolas Faure',
        atelierName: 'Atelier Faure',
        city: 'Castres',
        region: 'Occitanie',
        tier: 'Solo',
        plus: false,
        epvLabeled: false,
        ofgLabeled: true,
        specialities: ['Tissage main', 'Laine du Tarn'],
        story: "Tisserand main installé à Castres. Laine de moutons mérinos d'Arles, sourcée à 30 km.",
        photoUrl: 'https://placehold.co/256x256/oklch/60/0.13/195/png?text=Nicolas',
        websiteUrl: 'https://atelier-faure.fr',
        joinedAt: '2025-04-20T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-leila',
        displayName: 'Leïla Benamar',
        atelierName: 'Leïla Couture',
        city: 'Marseille',
        region: "Provence-Alpes-Côte d'Azur",
        tier: 'Solo',
        plus: true,
        epvLabeled: false,
        ofgLabeled: true,
        specialities: ['Couture sur mesure', 'Coton bio'],
        story: 'Atelier de couture sur mesure, fondé en 2022. Coton bio andalou et soie de Cévennes.',
        photoUrl: 'https://placehold.co/256x256/oklch/65/0.13/195/png?text=Leila',
        websiteUrl: 'https://leila-couture.fr',
        joinedAt: '2024-12-05T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-jules',
        displayName: 'Jules Pasquier',
        atelierName: 'Atelier Pasquier',
        city: 'Bordeaux',
        region: 'Nouvelle-Aquitaine',
        tier: 'Solo',
        plus: false,
        epvLabeled: false,
        ofgLabeled: false,
        specialities: ['Bonneterie', 'Coton recyclé'],
        story: 'Atelier de tricotage 100% coton recyclé, sourcé Hauts-de-France et Belgique.',
        photoUrl: 'https://placehold.co/256x256/oklch/64/0.18/45/png?text=Jules',
        websiteUrl: 'https://atelier-pasquier.fr',
        joinedAt: '2025-08-22T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-soraya',
        displayName: 'Soraya Maillard',
        atelierName: 'Maillard Maison',
        city: 'Reims',
        region: 'Grand Est',
        tier: 'Solo',
        plus: false,
        epvLabeled: false,
        ofgLabeled: false,
        specialities: ['Veste tailleur', 'Laine vierge'],
        story: 'Couturière diplômée École Boulle. Vestes tailleur sur mesure.',
        photoUrl: 'https://placehold.co/256x256/oklch/72/0.16/85/png?text=Soraya',
        websiteUrl: 'https://maillard-maison.fr',
        joinedAt: '2025-10-30T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-romain',
        displayName: 'Romain Petit',
        atelierName: 'Petit & Fils',
        city: 'Mazamet',
        region: 'Occitanie',
        tier: 'Studio',
        plus: true,
        epvLabeled: false,
        ofgLabeled: false,
        specialities: ['Tissage industriel', 'Laine'],
        story: 'Studio de tissage de 6 personnes à Mazamet. Capacité de série moyenne, qualité haute.',
        photoUrl: 'https://placehold.co/256x256/oklch/55/0.18/160/png?text=Romain',
        websiteUrl: 'https://petit-et-fils.fr',
        joinedAt: '2024-07-18T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Studio,
    },
    {
        id: 'art-pauline',
        displayName: 'Pauline Roux',
        atelierName: 'Pauline Roux Mode',
        city: 'Nantes',
        region: 'Pays de la Loire',
        tier: 'Solo',
        plus: false,
        epvLabeled: false,
        ofgLabeled: false,
        specialities: ['Pulls et chemises', 'Lin de France'],
        story: 'Créatrice indépendante installée à Nantes. Lin breton et chanvre.',
        photoUrl: 'https://placehold.co/256x256/oklch/55/0.20/15/png?text=Pauline',
        websiteUrl: 'https://paulineroux.fr',
        joinedAt: '2026-01-08T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Solo,
    },
    {
        id: 'art-maison-laurens',
        displayName: 'Maison Laurens',
        atelierName: 'Maison Laurens',
        city: 'Paris',
        region: 'Île-de-France',
        tier: 'Maison',
        plus: true,
        epvLabeled: true,
        ofgLabeled: true,
        specialities: ['Haute couture', 'Tailleur'],
        story: 'Maison parisienne fondée en 1978, EPV. Plusieurs ateliers (couture, broderie, plumasserie).',
        photoUrl: 'https://placehold.co/256x256/oklch/55/0.18/160/png?text=Laurens',
        websiteUrl: 'https://maison-laurens.fr',
        joinedAt: '2024-05-02T08:00:00Z',
        passportLimit: ARTISAN_PASSPORT_LIMIT.Maison,
    },
];

export interface ArtisanWithSlug extends Artisan {
    slug: string;
}

export const mockArtisansWithSlug: readonly ArtisanWithSlug[] = mockArtisans.map((a) => ({
    ...a,
    slug: slugify(a.displayName),
}));

const ARTISAN_BY_SLUG = new Map<string, ArtisanWithSlug>(mockArtisansWithSlug.map((a) => [a.slug, a]));
const ARTISAN_BY_ID = new Map<string, ArtisanWithSlug>(mockArtisansWithSlug.map((a) => [a.id, a]));

export function mockArtisanById(id: string): ArtisanWithSlug | undefined {
    return ARTISAN_BY_ID.get(id);
}

export function mockArtisanBySlug(slug: string): ArtisanWithSlug | undefined {
    return ARTISAN_BY_SLUG.get(slug);
}

export function mockArtisanByCity(city: string): readonly Artisan[] {
    return mockArtisans.filter((a) => a.city.toLowerCase() === city.toLowerCase());
}
