import type { CertificationRef } from '@lumiris/types';

// 12 certifs (8 Valid / 2 Expired / 2 Unverified) au mock NOW = 2026-04-30
export const mockCertificates: readonly CertificationRef[] = [
    {
        id: 'cert-gots-marie-lin',
        kind: 'GOTS',
        issuer: 'Ecocert',
        issuedAt: '2024-03-12T00:00:00Z',
        expiresAt: '2027-03-12T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/gots-marie-lin.pdf',
        scope: 'Lin breton — filature Quimper',
    },
    {
        id: 'cert-oeko-claire-laine',
        kind: 'OEKO-TEX',
        issuer: 'OEKO-TEX Standard 100',
        issuedAt: '2025-01-05T00:00:00Z',
        expiresAt: '2027-01-05T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/oeko-claire-laine.pdf',
        scope: 'Laine mérinos — Tarn',
    },
    {
        id: 'cert-epv-paul',
        kind: 'EPV',
        issuer: 'Institut National des Métiers d’Art',
        issuedAt: '2023-06-20T00:00:00Z',
        expiresAt: '2028-06-20T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/epv-paul.pdf',
        scope: 'Tannerie Chevreau — Graulhet',
    },
    {
        id: 'cert-ofg-marie',
        kind: 'OFG',
        issuer: 'Origine France Garantie',
        issuedAt: '2024-09-01T00:00:00Z',
        expiresAt: '2027-09-01T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/ofg-marie.pdf',
        scope: 'Atelier de Marie — Quimper',
    },
    {
        id: 'cert-grs-jules',
        kind: 'GRS',
        issuer: 'Textile Exchange',
        issuedAt: '2025-04-10T00:00:00Z',
        expiresAt: '2027-04-10T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/grs-jules.pdf',
        scope: 'Coton recyclé — filière Hauts-de-France',
    },
    {
        id: 'cert-bluesign-romain',
        kind: 'BLUESIGN',
        issuer: 'Bluesign Technologies',
        issuedAt: '2024-12-01T00:00:00Z',
        expiresAt: '2026-12-01T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/bluesign-romain.pdf',
        scope: 'Tissage Mazamet — chaîne énergétique',
    },
    {
        id: 'cert-iso14001-laurens',
        kind: 'ISO-14001',
        issuer: 'AFNOR Certification',
        issuedAt: '2024-05-15T00:00:00Z',
        expiresAt: '2027-05-15T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/iso14001-laurens.pdf',
        scope: 'Maison Laurens — Paris',
    },
    {
        id: 'cert-custom-amelie',
        kind: 'CUSTOM',
        customName: 'Maître Brodeur des Compagnons',
        issuer: 'Compagnons du Devoir',
        issuedAt: '2022-09-01T00:00:00Z',
        expiresAt: '2032-09-01T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/custom-amelie.pdf',
        scope: 'Amélie Berthier — Lyon',
    },

    // expired — ignorées par le scoring
    {
        id: 'cert-gots-pauline-expired',
        kind: 'GOTS',
        issuer: 'Ecocert',
        issuedAt: '2022-02-10T00:00:00Z',
        expiresAt: '2025-02-10T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/gots-pauline-expired.pdf',
        scope: 'Lin breton — Pauline Roux',
    },
    {
        id: 'cert-oeko-soraya-expired',
        kind: 'OEKO-TEX',
        issuer: 'OEKO-TEX Standard 100',
        issuedAt: '2021-11-01T00:00:00Z',
        expiresAt: '2024-11-01T00:00:00Z',
        verified: true,
        fileUrl: 'https://lumiris.fr/mock/cert/oeko-soraya-expired.pdf',
        scope: 'Laine vierge Reims',
    },

    // unverified — comptées ×0.5
    {
        id: 'cert-custom-leila-unverified',
        kind: 'CUSTOM',
        customName: 'Diplôme Couture Sur-Mesure',
        issuer: 'École de couture de Marseille',
        issuedAt: '2021-06-30T00:00:00Z',
        expiresAt: '2031-06-30T00:00:00Z',
        verified: false,
        fileUrl: 'https://lumiris.fr/mock/cert/custom-leila.pdf',
        scope: 'Leïla Benamar — diplôme initial',
    },
    {
        id: 'cert-ofg-nicolas-unverified',
        kind: 'OFG',
        issuer: 'Origine France Garantie',
        issuedAt: '2025-07-01T00:00:00Z',
        expiresAt: '2028-07-01T00:00:00Z',
        verified: false,
        fileUrl: 'https://lumiris.fr/mock/cert/ofg-nicolas.pdf',
        scope: 'Atelier Faure — en cours de vérification',
    },
];

export function mockCertificateById(id: string): CertificationRef | undefined {
    return mockCertificates.find((c) => c.id === id);
}
