import type { DPPRecord } from '@lumiris/types';

export const mockDpps: DPPRecord[] = [
    {
        id: 'DPP-2024-001',
        brand: 'Maison Lumiere',
        productName: 'Silk Draped Blazer',
        sku: 'ML-BLZ-001',
        status: 'Audit_Pending',
        submittedAt: '2024-12-14T09:23:00Z',
        auditorId: null,
        dataIntegrity: 87,
        missingFields: ['recycled_content_percentage', 'water_usage_liters'],
        supplierFactory: 'Tessuti Milano SRL',
        carbonScore: 4.2,
        rawData: {
            product_name: 'Silk Draped Blazer',
            material_composition: '78% Silk, 22% Organic Cotton',
            country_of_origin: 'Italy',
            manufacturer: 'Tessuti Milano SRL',
            recycled_content_percentage: null,
            water_usage_liters: null,
            carbon_footprint_kg: 4.2,
            durability_score: 'A',
            repairability_index: 7.8,
            eu_compliance_version: 'ESPR-2024-v2',
        },
    },
    {
        id: 'DPP-2024-002',
        brand: 'Atelier Nord',
        productName: 'Recycled Wool Overcoat',
        sku: 'AN-OVC-014',
        status: 'Flagged_Anomalies',
        submittedAt: '2024-12-13T14:11:00Z',
        auditorId: 'AUD-003',
        dataIntegrity: 62,
        missingFields: ['carbon_footprint_kg', 'repairability_index', 'durability_score'],
        supplierFactory: 'Nordic Textiles AB',
        carbonScore: null,
        rawData: {
            product_name: 'Recycled Wool Overcoat',
            material_composition: '65% Recycled Wool, 35% Polyester',
            country_of_origin: 'Sweden',
            manufacturer: 'Nordic Textiles AB',
            recycled_content_percentage: 65,
            water_usage_liters: 2100,
            carbon_footprint_kg: null,
            durability_score: null,
            repairability_index: null,
            eu_compliance_version: 'ESPR-2024-v2',
        },
    },
    {
        id: 'DPP-2024-003',
        brand: 'Verde Collective',
        productName: 'Organic Linen Shirt',
        sku: 'VC-LSH-092',
        status: 'Published_Live',
        submittedAt: '2024-12-10T08:45:00Z',
        auditorId: 'AUD-001',
        dataIntegrity: 100,
        missingFields: [],
        supplierFactory: 'EcoWeave Portugal Lda',
        carbonScore: 1.8,
        rawData: {
            product_name: 'Organic Linen Shirt',
            material_composition: '100% Organic Linen',
            country_of_origin: 'Portugal',
            manufacturer: 'EcoWeave Portugal Lda',
            recycled_content_percentage: 0,
            water_usage_liters: 450,
            carbon_footprint_kg: 1.8,
            durability_score: 'A+',
            repairability_index: 9.1,
            eu_compliance_version: 'ESPR-2024-v2',
        },
    },
    {
        id: 'DPP-2024-004',
        brand: 'Maison Lumiere',
        productName: 'Cashmere Pullover',
        sku: 'ML-CPL-055',
        status: 'Draft',
        submittedAt: '2024-12-15T16:02:00Z',
        auditorId: null,
        dataIntegrity: 34,
        missingFields: [
            'material_composition',
            'carbon_footprint_kg',
            'water_usage_liters',
            'durability_score',
            'repairability_index',
        ],
        supplierFactory: 'Tessuti Milano SRL',
        carbonScore: null,
        rawData: {
            product_name: 'Cashmere Pullover',
            material_composition: null,
            country_of_origin: 'Italy',
            manufacturer: 'Tessuti Milano SRL',
            recycled_content_percentage: null,
            water_usage_liters: null,
            carbon_footprint_kg: null,
            durability_score: null,
            repairability_index: null,
            eu_compliance_version: 'ESPR-2024-v2',
        },
    },
    {
        id: 'DPP-2024-005',
        brand: 'Atelier Nord',
        productName: 'Hemp Canvas Tote',
        sku: 'AN-TOT-027',
        status: 'Published_Live',
        submittedAt: '2024-12-09T11:30:00Z',
        auditorId: 'AUD-002',
        dataIntegrity: 98,
        missingFields: [],
        supplierFactory: 'Nordic Textiles AB',
        carbonScore: 0.9,
        rawData: {
            product_name: 'Hemp Canvas Tote',
            material_composition: '100% Organic Hemp',
            country_of_origin: 'Finland',
            manufacturer: 'Nordic Textiles AB',
            recycled_content_percentage: 0,
            water_usage_liters: 120,
            carbon_footprint_kg: 0.9,
            durability_score: 'B+',
            repairability_index: 8.4,
            eu_compliance_version: 'ESPR-2024-v2',
        },
    },
    {
        id: 'DPP-2024-006',
        brand: 'Verde Collective',
        productName: 'Bamboo Knit Sweater',
        sku: 'VC-BKS-041',
        status: 'Grade_E',
        submittedAt: '2024-12-12T13:17:00Z',
        auditorId: 'AUD-001',
        dataIntegrity: 22,
        missingFields: [
            'material_composition',
            'recycled_content_percentage',
            'water_usage_liters',
            'carbon_footprint_kg',
            'durability_score',
            'repairability_index',
            'country_of_origin',
        ],
        supplierFactory: 'Unknown',
        carbonScore: null,
        rawData: {
            product_name: 'Bamboo Knit Sweater',
            material_composition: null,
            country_of_origin: null,
            manufacturer: 'Unknown',
            recycled_content_percentage: null,
            water_usage_liters: null,
            carbon_footprint_kg: null,
            durability_score: null,
            repairability_index: null,
            eu_compliance_version: null,
        },
    },
    {
        id: 'DPP-2024-007',
        brand: 'Lux Fabrica',
        productName: 'Tencel Midi Dress',
        sku: 'LF-TMD-018',
        status: 'Audit_Pending',
        submittedAt: '2024-12-14T15:44:00Z',
        auditorId: null,
        dataIntegrity: 91,
        missingFields: ['repairability_index'],
        supplierFactory: 'EcoWeave Portugal Lda',
        carbonScore: 2.1,
        rawData: {
            product_name: 'Tencel Midi Dress',
            material_composition: '90% Tencel, 10% Elastane',
            country_of_origin: 'Portugal',
            manufacturer: 'EcoWeave Portugal Lda',
            recycled_content_percentage: 0,
            water_usage_liters: 380,
            carbon_footprint_kg: 2.1,
            durability_score: 'A',
            repairability_index: null,
            eu_compliance_version: 'ESPR-2024-v2',
        },
    },
    {
        id: 'DPP-2024-008',
        brand: 'Lux Fabrica',
        productName: 'Merino Base Layer',
        sku: 'LF-MBL-033',
        status: 'Audit_Pending',
        submittedAt: '2024-12-15T10:08:00Z',
        auditorId: null,
        dataIntegrity: 79,
        missingFields: ['water_usage_liters', 'durability_score'],
        supplierFactory: 'Tessuti Milano SRL',
        carbonScore: 3.5,
        rawData: {
            product_name: 'Merino Base Layer',
            material_composition: '100% Merino Wool',
            country_of_origin: 'Italy',
            manufacturer: 'Tessuti Milano SRL',
            recycled_content_percentage: 0,
            water_usage_liters: null,
            carbon_footprint_kg: 3.5,
            durability_score: null,
            repairability_index: 6.2,
            eu_compliance_version: 'ESPR-2024-v2',
        },
    },
];

export function mockDppById(id: string): DPPRecord | undefined {
    return mockDpps.find((dpp) => dpp.id === id);
}

export function mockDppBySku(sku: string): DPPRecord | undefined {
    return mockDpps.find((dpp) => dpp.sku === sku);
}
