import type { JournalArticle } from '@lumiris/types';

export const mockJournalArticles: JournalArticle[] = [
    {
        id: 'ART-FR-001',
        title: 'Le DPP textile en 2028 : ce que l’ESPR va changer pour vos passeports',
        category: 'reglementation',
        status: 'Published',
        author: 'Claire Dubois',
        createdAt: '2026-03-04T08:00:00Z',
        updatedAt: '2026-03-08T11:30:00Z',
        excerpt:
            'En 2028, chaque vêtement vendu en Europe devra être accompagné d’un Digital Product Passport. Décryptage des champs obligatoires et de leur impact sur les ateliers français.',
        readTime: '9 min',
        body: 'En 2028, chaque vêtement, chaque chaussure, chaque accessoire textile vendu sur le marché européen devra exposer un Digital Product Passport. Pour les artisans français, ce n’est pas une contrainte de plus : c’est l’occasion de rendre visible une chaîne de valeur déjà courte et déjà documentée.\n\nLe règlement ESPR définit des champs minimaux : composition, origine, durabilité, réparabilité, fin de vie. LUMIRIS pré-remplit la moitié de ces champs à partir des factures fournisseurs scannées et du dossier EPV existant. Restent les preuves : photos, gestes, certifications. C’est ce qui fait la différence entre un passeport conforme et un passeport qui inspire confiance.\n\nDans cet article, nous détaillons chacun des dix champs ESPR, leur traduction en items LUMIRIS et le calendrier officiel - y compris le sursis prévu pour les artisans inscrits au Répertoire des Métiers.',
    },
    {
        id: 'ART-FR-002',
        title: 'Glossaire AGEC / ESPR / GS1 : tous les sigles, en clair',
        category: 'reglementation',
        status: 'Published',
        author: 'Maxime Laurent',
        createdAt: '2026-03-18T09:30:00Z',
        updatedAt: '2026-03-19T10:00:00Z',
        excerpt:
            'AGEC, ESPR, EPR, GS1, GTIN, EPV, OFG : un guide compact pour parler la langue du DPP textile sans s’y perdre.',
        readTime: '6 min',
        body: 'Si vous êtes artisan et que vous avez ouvert ne serait-ce qu’un PDF du Ministère sur le DPP, vous avez vu défiler des sigles. Ce glossaire les remet à plat, dans l’ordre où ils touchent votre quotidien.\n\nAGEC - la loi Anti-Gaspillage pour une Économie Circulaire (France, 2020) impose les premiers affichages d’information sur les produits neufs. C’est le socle français.\n\nESPR - l’Ecodesign for Sustainable Products Regulation (UE, 2024) prend la suite à l’échelle européenne. Plus large, plus normatif, et c’est lui qui crée le DPP.\n\nGS1 - l’organisme international qui standardise les codes-barres et les identifiants produits. Le DPP s’appuie sur GS1 pour qu’un même passeport soit lisible partout.\n\nGTIN - le numéro à 13 chiffres derrière le code-barres EAN. Chaque variante de produit a le sien.\n\nEPV - Entreprise du Patrimoine Vivant, label décerné par l’État français aux ateliers qui détiennent un savoir-faire rare.\n\nOFG - Origine France Garantie, label privé qui certifie qu’au moins 50 % du prix de revient unitaire est français.\n\nNous mettrons ce glossaire à jour à chaque évolution réglementaire - abonnez-vous au flux pour ne rien rater.',
    },
    {
        id: 'ART-FR-003',
        title: 'Pourquoi LUMIRIS ne vendra jamais ses scores',
        category: 'reglementation',
        status: 'Published',
        author: 'Léa Marchand',
        createdAt: '2026-04-08T07:00:00Z',
        updatedAt: '2026-04-08T07:00:00Z',
        excerpt:
            'Notre charte d’indépendance, en sept articles. Un score Iris ne se monnaie pas - sinon il ne signifie plus rien.',
        readTime: '4 min',
        body: 'LUMIRIS s’est créé en réaction. En réaction à des labels privés qui notent leurs propres clients. En réaction à des plateformes qui empilent les badges sponsorisés. Nous avons écrit cette charte d’indépendance pour que ce soit clair, en interne et pour vous.\n\nArticle 1 - Aucun artisan, aucune marque, aucun fournisseur ne peut acheter, négocier ou influencer son score Iris. Le score est calculé par algorithme déterministe, à partir des données vérifiées du passeport.\n\nArticle 2 - Notre modèle économique est public : abonnements ATELIER (29 / 79 / 149 €) et abonnements LOCAL retoucheurs. Aucun revenu ne provient des marques notées.\n\nArticle 3 - Nous ne plaçons jamais d’encart sponsorisé sur une fiche artisan ou sur une fiche produit. Le seul placement payant est l’add-on ATELIER+, qui modifie la visibilité dans l’annuaire - jamais le score.\n\nArticle 4 - Nos algorithmes sont open-source. Le code de @lumiris/core est public sur GitHub. N’importe qui peut auditer la formule.\n\nArticle 5 - Nos jeux de données de référence (baselines carbone, baselines eau, seuils de réparabilité) sont publiés et versionnés. Les changements sont annoncés 90 jours avant application.\n\nArticle 6 - En cas de doute fondé sur l’indépendance d’un score, l’utilisateur peut saisir une commission externe. Nous publions les saisines et les décisions.\n\nArticle 7 - Si nous ne respectons pas l’un de ces six premiers articles, nous nous engageons à fermer le service.',
    },
    {
        id: 'ART-FR-004',
        title: 'Portrait - Marie Le Goff, le lin breton à la main',
        category: 'portrait-artisan',
        status: 'Published',
        author: 'Léa Marchand',
        createdAt: '2026-04-12T10:00:00Z',
        updatedAt: '2026-04-12T10:00:00Z',
        excerpt:
            'Quimper, atelier 18 m². Marie coupe au mètre, coud à la machine droite et signe ses pièces. Reportage.',
        readTime: '7 min',
        body: 'Quimper, premier mardi d’avril. Le ciel est d’un gris breton sans concession. Marie ouvre l’atelier à 8 h 30, allume la cafetière, sort le mètre ruban et déroule la pièce de lin. Vingt-trois mètres de fil bretagne tissé à Locronan, livrés la veille. C’est ce que verront ses clients sur le passeport - la facture est déjà scannée, le numéro de lot inscrit.\n\nMarie a appris la couture aux Compagnons du Devoir, à Tours, entre 2014 et 2019. Elle s’est installée à Quimper l’été suivant, dans un local de 18 mètres carrés rue Kéréon. Une machine à coudre droite Pfaff, une surjeteuse Juki, une planche à découper, un mannequin. Pas de stock. Chaque pièce part sur commande, en moins de 30 jours.\n\nCe qui frappe quand on la regarde travailler, c’est la lenteur. La coupe prend 40 minutes, l’épaule 25, le poignet 15. Une chemise demande quatre heures et demie. Au prix de vente public - 240 € - on est largement sous le SMIC horaire si on intègre le temps administratif. « LUMIRIS m’a fait gagner deux heures par semaine sur le passeport », dit-elle. « Avant je remplissais Origine France à la main sur Excel, je n’avais aucune trace photo. »\n\nMarie est labellisée Origine France Garantie depuis 2024. Elle vise EPV pour 2027 - il lui manque l’ancienneté minimale (5 ans). Le score Iris de sa chemise lin (passeport pass-marie-001) atteint un grade A : composition documentée, fournisseur identifié, certifications GOTS valides, six étapes de fabrication photographiées, garantie 24 mois. C’est le scénario nominal.\n\nCe n’est pas du marketing. C’est du temps réel et de la main. Quand vous scannez le QR au revers de la chemise, ce que vous voyez s’est passé pour de vrai, à Quimper, devant une machine droite, par une couturière qui s’appelle Marie.',
    },
    {
        id: 'ART-FR-005',
        title: 'Métiers d’art textile : les 14 spécialités reconnues par l’INMA',
        category: 'savoir-faire',
        status: 'Published',
        author: 'Claire Dubois',
        createdAt: '2026-04-20T08:30:00Z',
        updatedAt: '2026-04-21T09:00:00Z',
        excerpt:
            'Couturier, tisserand, bonnetier, brodeur, chausseur… L’INMA recense 281 métiers. En voici les 14 qui touchent au textile.',
        readTime: '8 min',
        body: 'L’Institut National des Métiers d’Art (INMA), créé en 1889 et placé sous la tutelle des ministères de la Culture et de l’Économie, recense officiellement 281 métiers d’art en France. Sur ce total, quatorze relèvent directement du textile et de l’habillement. Ils structurent la cartographie LUMIRIS et les filtres de l’annuaire.\n\nCouturier flou, couturier tailleur, modéliste, plumassier, brodeur, dentellier, tisserand, bonnetier, passementier, gantier, chapelier, chausseur, maroquinier, sellier-harnacheur. Quatorze noms qui cachent autant de gestes. Le couturier flou travaille en volume, le tailleur en aplat. Le bonnetier maille là où le tisserand croise. Le plumassier - il en reste une douzaine en France - assemble la plume pour la haute couture parisienne.\n\nÊtre reconnu comme métier d’art ouvre des droits : statut fiscal spécifique (BNC sur option), accès au label Entreprise du Patrimoine Vivant, financements régionaux dédiés. Cela impose aussi une exigence - la plupart des organismes professionnels (FFC, UFIH, CFM) demandent un diplôme métier (CAP, BMA, DMA) ou une équivalence Compagnons.\n\nDans LUMIRIS, le filtre « spécialité » de l’annuaire reprend ces quatorze libellés, regroupés en cinq familles (couture, tissage, bonneterie, chausseur, broderie) pour rester lisible côté consommateur. Un artisan peut cocher plusieurs spécialités - la majorité de nos pilotes en cumulent deux ou trois.',
    },
    {
        id: 'ART-FR-006',
        title: 'AGEC - la pénalité 2027 sur l’affichage environnemental, mode d’emploi',
        category: 'reglementation',
        status: 'Published',
        author: 'Maxime Laurent',
        createdAt: '2026-04-24T11:00:00Z',
        updatedAt: '2026-04-25T15:30:00Z',
        excerpt:
            'À partir du 1er janvier 2027, l’absence d’affichage environnemental sur les vêtements neufs sera sanctionnée. Décryptage des seuils et des recours.',
        readTime: '5 min',
        body: 'La loi AGEC (Anti-Gaspillage pour une Économie Circulaire), promulguée le 10 février 2020, impose progressivement l’affichage environnemental sur les produits textiles neufs vendus en France. Le calendrier est cadencé : volontaire jusqu’en 2024, recommandé en 2025-2026, obligatoire à partir du 1er janvier 2027 pour les acteurs au chiffre d’affaires supérieur à 50 millions d’euros, étendu à tous les vendeurs en 2029.\n\nL’affichage AGEC repose sur cinq critères chiffrés : empreinte carbone (kg CO₂e), consommation d’eau (litres), pourcentage de matière recyclée, durabilité (mois de garantie), réparabilité (note sur 10). LUMIRIS calcule ces cinq valeurs automatiquement à partir des données du passeport.\n\nLes sanctions ? Pour un manquement constaté, la DGCCRF peut prononcer une amende administrative jusqu’à 3 000 € pour une personne physique et 15 000 € pour une personne morale. Le retrait de la pièce de la vente est possible mais rare. La sanction effective dépend du volume vendu sans affichage.\n\nLes artisans inscrits au Répertoire des Métiers (RM) bénéficient d’un sursis de deux ans - applicable jusqu’au 31 décembre 2028. Ce sursis ne couvre pas les ateliers exerçant uniquement sous le statut d’auto-entrepreneur en activité libérale. La sécurité juridique consiste à publier dès aujourd’hui un passeport AGEC-compatible, ce que LUMIRIS génère par défaut.\n\nDeux recours en cas de contrôle : démonstration de bonne foi (passeport en cours de complétion, déposé auprès d’une plateforme reconnue) et droit à régularisation sous 30 jours. C’est exactement ce que documente le statut « En cours de complétion » LUMIRIS - visible côté consommateur sans pénaliser l’artisan.',
    },
    {
        id: 'ART-001',
        title: 'Understanding the EU ESPR: What Fashion Brands Need to Know',
        category: 'reglementation',
        status: 'Published',
        author: 'Claire Dubois',
        createdAt: '2024-12-10T08:00:00Z',
        updatedAt: '2024-12-12T14:30:00Z',
        excerpt:
            'A deep dive into the European Sustainability Product Regulation and its implications for the fashion industry.',
        readTime: '8 min',
        body: 'The Ecodesign for Sustainable Products Regulation (ESPR) sets the legal framework for the Digital Product Passport across the European Union. From 2028 onwards, every textile garment placed on the EU market must expose a passport carrying composition, durability, repairability and end-of-life data.\n\nThis article is a working draft kept on the admin CMS - public version will be published in French.',
    },
    {
        id: 'ART-002',
        title: 'How Transparency Builds Consumer Trust in 2025',
        category: 'entretien',
        status: 'Published',
        author: 'Maxime Laurent',
        createdAt: '2024-12-08T10:15:00Z',
        updatedAt: '2024-12-08T10:15:00Z',
        excerpt:
            'Exploring the growing demand for supply chain visibility and how brands can leverage DPP data to connect with conscious consumers.',
        readTime: '5 min',
        body: 'Consumer expectations on textile traceability have shifted in less than five years. Where a vague "Made in France" label once sufficed, shoppers now expect documented fibre origin, atelier identity, repair channel and carbon footprint.\n\nThis is a working draft kept on the admin CMS - see the French Journal for the published narrative.',
    },
    {
        id: 'ART-003',
        title: 'Inside Our Audit Process: From Raw Data to Published Passport',
        category: 'reglementation',
        status: 'Draft',
        author: 'Claire Dubois',
        createdAt: '2024-12-14T09:00:00Z',
        updatedAt: '2024-12-15T11:22:00Z',
        excerpt:
            'A behind-the-scenes look at how LUMIRIS verifies supplier data, cross-checks certificates, and ensures compliance.',
        readTime: '12 min',
        body: 'Working draft - this article describes the founder/content-manager review pipeline that turns an InCompletion passport into a Published one. Will be published once the audit playbook is stable.',
    },
    {
        id: 'ART-004',
        title: 'Carbon Scoring Methodology: Our Approach Explained',
        category: 'savoir-faire',
        status: 'Draft',
        author: 'Maxime Laurent',
        createdAt: '2024-12-15T14:00:00Z',
        updatedAt: '2024-12-15T14:00:00Z',
        excerpt: 'Breaking down how carbon footprint scores are calculated and verified across the supply chain.',
        readTime: '10 min',
        body: 'Working draft - pending baseline v1.2.0 (carbon coefficients ADEME 2025). Will detail the fibre × mass model and how declared carbonKg overrides the calculation.',
    },
    {
        id: 'ART-005',
        title: 'The Rise of Circular Fashion: Repair, Reuse, Recycle',
        category: 'entretien',
        status: 'Scheduled',
        author: 'Claire Dubois',
        createdAt: '2024-12-13T16:45:00Z',
        updatedAt: '2024-12-14T09:10:00Z',
        excerpt: 'How the repairability index is changing the way consumers think about fashion longevity.',
        readTime: '6 min',
        body: 'Working draft - scheduled for publication once the LUMIRIS Local network reaches 50 referenced repairers. Will report on first-year usage data and median delay times.',
    },
];

export function mockJournalArticleById(id: string): JournalArticle | undefined {
    return mockJournalArticles.find((a) => a.id === id);
}
