import type { Repairer } from '@lumiris/types';

// 15 retoucheurs (8 Local payant, 7 free) - persona Mehdi inclus, spécialités mixées
export const mockRepairers: readonly Repairer[] = [
    {
        id: 'rtc-mehdi',
        displayName: 'Mehdi Bouzid',
        atelierName: 'Mehdi Retouches',
        city: 'Lyon',
        region: 'Auvergne-Rhône-Alpes',
        distanceKm: 0,
        specialities: ['alteration', 'lining'],
        certifications: [],
        avgRating: 4.8,
        reviewCount: 142,
        avgDelayDays: 3,
        priceRange: { min: 12, max: 90, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2024-09-10T08:00:00Z',
    },
    {
        id: 'rtc-002',
        displayName: 'Sophie Nguyen',
        atelierName: 'Atelier Sophie',
        city: 'Lyon',
        region: 'Auvergne-Rhône-Alpes',
        distanceKm: 1.5,
        specialities: ['alteration', 'embroidery'],
        certifications: [],
        avgRating: 4.6,
        reviewCount: 87,
        avgDelayDays: 4,
        priceRange: { min: 15, max: 120, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2025-01-20T08:00:00Z',
    },
    {
        id: 'rtc-003',
        displayName: 'Karim Mahmoudi',
        atelierName: 'Cordonnerie du Rhône',
        city: 'Lyon',
        region: 'Auvergne-Rhône-Alpes',
        distanceKm: 2.1,
        specialities: ['shoe-repair', 'leather'],
        certifications: [],
        avgRating: 4.9,
        reviewCount: 210,
        avgDelayDays: 2,
        priceRange: { min: 20, max: 140, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2024-06-05T08:00:00Z',
    },
    {
        id: 'rtc-004',
        displayName: 'Emma Lefèvre',
        atelierName: "L'aiguille fine",
        city: 'Quimper',
        region: 'Bretagne',
        distanceKm: 0.8,
        specialities: ['alteration', 'lining'],
        certifications: [],
        avgRating: 4.7,
        reviewCount: 64,
        avgDelayDays: 5,
        priceRange: { min: 10, max: 70, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2025-03-12T08:00:00Z',
    },
    {
        id: 'rtc-005',
        displayName: 'Yann Le Bras',
        atelierName: 'Yann Cuir',
        city: 'Quimper',
        region: 'Bretagne',
        distanceKm: 1.2,
        specialities: ['leather', 'shoe-repair'],
        certifications: [],
        avgRating: 4.5,
        reviewCount: 38,
        avgDelayDays: 6,
        priceRange: { min: 18, max: 100, currency: 'EUR' },
        localSubscribed: false,
        joinedAt: '2025-11-08T08:00:00Z',
    },
    {
        id: 'rtc-006',
        displayName: 'Hélène Marchetti',
        atelierName: 'Hélène Couture',
        city: 'Quimper',
        region: 'Bretagne',
        distanceKm: 2.4,
        specialities: ['alteration', 'embroidery'],
        certifications: [],
        avgRating: 4.4,
        reviewCount: 29,
        avgDelayDays: 7,
        priceRange: { min: 12, max: 80, currency: 'EUR' },
        localSubscribed: false,
        joinedAt: '2025-12-01T08:00:00Z',
    },
    {
        id: 'rtc-007',
        displayName: 'Inès Almeida',
        atelierName: 'Atelier Inès',
        city: 'Romans-sur-Isère',
        region: 'Auvergne-Rhône-Alpes',
        distanceKm: 0.5,
        specialities: ['shoe-repair', 'leather'],
        certifications: [],
        avgRating: 4.8,
        reviewCount: 96,
        avgDelayDays: 3,
        priceRange: { min: 18, max: 130, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2024-08-14T08:00:00Z',
    },
    {
        id: 'rtc-008',
        displayName: 'Bastien Rivet',
        atelierName: 'Rivet Cordonnerie',
        city: 'Romans-sur-Isère',
        region: 'Auvergne-Rhône-Alpes',
        distanceKm: 1.0,
        specialities: ['shoe-repair'],
        certifications: [],
        avgRating: 4.6,
        reviewCount: 71,
        avgDelayDays: 4,
        priceRange: { min: 15, max: 95, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2025-02-28T08:00:00Z',
    },
    {
        id: 'rtc-009',
        displayName: 'Manon Chassagne',
        atelierName: 'Manon Brodeuse',
        city: 'Lille',
        region: 'Hauts-de-France',
        distanceKm: 0.3,
        specialities: ['embroidery', 'alteration'],
        certifications: [],
        avgRating: 4.9,
        reviewCount: 53,
        avgDelayDays: 4,
        priceRange: { min: 14, max: 110, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2025-05-19T08:00:00Z',
    },
    {
        id: 'rtc-010',
        displayName: 'Olivier Marchand',
        atelierName: 'Marchand Retouche',
        city: 'Marseille',
        region: "Provence-Alpes-Côte d'Azur",
        distanceKm: 1.4,
        specialities: ['alteration', 'lining'],
        certifications: [],
        avgRating: 4.3,
        reviewCount: 22,
        avgDelayDays: 6,
        priceRange: { min: 11, max: 75, currency: 'EUR' },
        localSubscribed: false,
        joinedAt: '2025-10-04T08:00:00Z',
    },
    {
        id: 'rtc-011',
        displayName: 'Léa Dujardin',
        atelierName: 'Léa Atelier',
        city: 'Bordeaux',
        region: 'Nouvelle-Aquitaine',
        distanceKm: 0.6,
        specialities: ['alteration', 'embroidery'],
        certifications: [],
        avgRating: 4.5,
        reviewCount: 41,
        avgDelayDays: 5,
        priceRange: { min: 12, max: 85, currency: 'EUR' },
        localSubscribed: false,
        joinedAt: '2025-09-25T08:00:00Z',
    },
    {
        id: 'rtc-012',
        displayName: 'Hugo Tavernier',
        atelierName: 'Hugo Cuir',
        city: 'Paris',
        region: 'Île-de-France',
        distanceKm: 0.9,
        specialities: ['leather', 'shoe-repair'],
        certifications: [],
        avgRating: 4.7,
        reviewCount: 188,
        avgDelayDays: 4,
        priceRange: { min: 25, max: 200, currency: 'EUR' },
        localSubscribed: true,
        joinedAt: '2024-04-15T08:00:00Z',
    },
    {
        id: 'rtc-013',
        displayName: 'Camille Rouet',
        atelierName: 'Camille Couture',
        city: 'Paris',
        region: 'Île-de-France',
        distanceKm: 1.8,
        specialities: ['alteration', 'lining'],
        certifications: [],
        avgRating: 4.4,
        reviewCount: 35,
        avgDelayDays: 5,
        priceRange: { min: 18, max: 130, currency: 'EUR' },
        localSubscribed: false,
        joinedAt: '2025-07-22T08:00:00Z',
    },
    {
        id: 'rtc-014',
        displayName: 'Élodie Vasseur',
        atelierName: 'Atelier Vasseur',
        city: 'Reims',
        region: 'Grand Est',
        distanceKm: 1.1,
        specialities: ['alteration'],
        certifications: [],
        avgRating: 4.2,
        reviewCount: 18,
        avgDelayDays: 7,
        priceRange: { min: 9, max: 60, currency: 'EUR' },
        localSubscribed: false,
        joinedAt: '2026-02-14T08:00:00Z',
    },
    {
        id: 'rtc-015',
        displayName: 'Pierre Chassagne',
        atelierName: 'Chassagne Cuir',
        city: 'Castres',
        region: 'Occitanie',
        distanceKm: 1.5,
        specialities: ['leather', 'shoe-repair'],
        certifications: [],
        avgRating: 4.5,
        reviewCount: 27,
        avgDelayDays: 5,
        priceRange: { min: 16, max: 100, currency: 'EUR' },
        localSubscribed: false,
        joinedAt: '2025-08-30T08:00:00Z',
    },
];

export function mockRepairerById(id: string): Repairer | undefined {
    return mockRepairers.find((r) => r.id === id);
}

export function mockRepairersByCity(city: string): readonly Repairer[] {
    return mockRepairers.filter((r) => r.city.toLowerCase() === city.toLowerCase());
}
